def create_findy2_state():
    """Return fresh mutable state for one FINDY2 app session."""
    return {
        "saved_ids": set(),
        "selected_tab": 0,
        "selected_category": None,
        "selected_beauty_category": "헤어",
        "search_text": "",
        "search_results": [],
        "search_sort": "rating",
        "recent_searches": ["레이어드컷", "여쿨 메이크업", "네일 유지력", "프로필 촬영", "반영구 눈썹"],
        "recommendation_entry": None,
        "detail_artist": None,
        "detail_back_target": "home",
        "ad_index": 0,
        "ad_task_started": False,
        "snap_index": 0,
        "snap_task_started": False,
        "snap_cards_row": None,
        "review_index": 0,
        "review_cards_column": None,
        "overlay": None,
        "left_menu_expanded": None,
        "snap_layout_mode": 3,
        "snap_sort_mode": "popular",
        "snap_filter": "전체",
        "snap_detail_item": None,
        "snap_liked_ids": set(),
        "snap_saved_ids": set(),
        "snap_followed_creators": set(),
        "written_snaps": [],
        "community_posts": [],
        "community_board_type": "자유",
        "community_category_filter": "전체",
        "community_sort_mode": "popular",
        "community_write_type": "질문",
        "community_liked_ids": set(),
        "community_saved_ids": set(),
        "content_comments": {},
        "comment_liked_ids": set(),
        "answered_question_ids": set(),
        "content_reports": [],
        "admin_action_logs": [],
        "written_videos": [],
        "video_comments": {},
        "video_comments_open": False,
        "video_liked_keys": set(),
        "video_saved_keys": set(),
        "video_followed_creators": set(),
        "video_reposted_keys": set(),
        "video_shared_keys": set(),
        "video_paused_keys": set(),
        "video_more_open": False,
        "video_category_filter": "전체",
        "video_detail_item": None,
        "my_content_type": "전체",
        "saved_content_type": "전체",
        "content_detail_item": None,
        "artist_available_slots": ["11:00", "12:30", "15:00", "17:30", "19:00"],
        "current_user": None,
        "reservation_form": {
            "artist_id": None,
            "artist_name": "",
            "job": "",
            "category": "",
            "date": None,
            "time": None,
            "note": "",
        },
        "reservation_history": [],
        "written_reviews": [],
        "review_target": None,
        "review_reports": [],
        "review_admin_filter": "pending",
        "review_admin_memo": "",
        "admin_notices": [],
        "admin_center_tab": "overview",
        "api_sync_state": {
            "lastHealth": "",
            "lastError": "",
            "lastCheckedAt": "",
        },
        "last_completed_reservation": None,
        "reservation_month_offset": 0,
        "dismissed_upcoming_notice_id": None,
        "notification_read_at": None,
        "app_settings": {
            "pushNotifications": True,
            "activityNotifications": True,
            "reviewNotifications": True,
            "soundEffects": True,
            "vibration": True,
            "locationBasedRecommendations": False,
            "privateProfile": False,
            "activityStatus": True,
            "personalizedRecommendations": True,
            "autoPlayVideos": True,
            "dataSaver": False,
            "highContrastText": False,
            "cacheSize": "0MB",
            "language": "한국어",
            "region": "대한민국",
        },
        "consent_records": [],
        "point_wallets": {},
        "point_transactions": [],
        "inquiry_history": [],
        "inquiry_draft": {
            "category": "계정/이용",
            "title": "",
            "content": "",
        },
        "user_profile": {
            "name": "FINDY 회원",
            "username": "findy_user",
            "pronouns": "",
            "bio": "나에게 맞는 뷰티 스타일을 찾고 있어요.",
            "link": "",
            "banner": "",
            "gender": "선택 안 함",
            "profileCategory": "뷰티 관심 사용자",
            "contactOption": "비공개",
            "actionButton": "비활성화",
            "profileVisibility": "전체 공개",
            "facebook": "연결 안 됨",
            "interestedFields": ["메이크업", "헤어"],
            "styleKeywords": ["차가운", "귀여운"],
            "skinType": "지성",
            "makeupConcern": "지속력",
            "hairConcern": "볼륨",
            "personalTone": "쿨톤",
            "budgetRange": "상관없음",
            "locationPreference": "내 주변",
            "algorithmMemo": "관심 분야와 스타일에 맞춰 추천을 받고 싶어요.",
        },
        "location_state": {
            "enabled": False,
            "permission": "unknown",
            "locationPermissionStatus": "not_requested",
            "locationEnabled": False,
            "selectedRegion": "",
            "label": "위치 미설정",
            "lat": None,
            "lng": None,
            "updatedAt": "",
            "source": "",
        },
        "profile_edit_draft": None,
        "profile_activity_tab": "전체",
        "message_threads": [],
        "active_message_thread_id": None,
        "message_draft": {
            "category": "스타일 상담",
            "content": "",
        },
        "message_reply_draft": "",
        "message_back_target": None,
        "completion_feedback": None,
        "reported_content_ids": set(),
        "hidden_content_ids": set(),
        "my_info_expanded_sections": set(),
        "page_history": [],
        "_last_rendered_page": None,
    }
